#!/bin/bash

echo
echo -e "\e[1;36m-----------使用GitMoji-cli编辑提交------------\e[0m"
echo "           遵循 Gitmoji"
echo "           https://gitmoji.dev/"
echo -e "\e[1;36m----------------------------------------------\e[0m"

exec < /dev/tty
pnpm gitmoji --hook $1 $2
